### ISSUE TITLE
Rename default branch to main

### ISSUE THREAD

**Issue by swissbuechi** [Homebrew/homebrew-autoupdate#111]
The default branch name should be changed from `master` to `main`.

**Comment by dawidd6** [comment]
Why? It's just a name. I think almost every Homebrew repository has a master branch.

**Comment by swissbuechi** [comment]
Github und Gitlab decided in 2020 that the term `master` refers to slavery.

So the new default name for de the default branch should always be `main`.

I just saw that every repo from homebrew still uses `master`. So maybe you can ignore this issue...
