### ISSUE TITLE
Unlike the built in autoupdate, Homebrew Autoupdate does not show the list of outdated packages

### ISSUE THREAD

**Issue by keyansheng** [Homebrew/homebrew-autoupdate#122]
And when you interact with Homebrew, it doesn't show the list of outdated packages since Homebrew Autoupdate already ran `brew update` for you and hid the list of packages from you.

This makes it easier to miss updates than using the built in autoupdate, which is the opposite of what Homebrew Autoupdate is trying to achieve.

I know that Homebrew Autoupdate can automate both updates and upgrades, but I would like to manually review upgrades before applying them. All I need from Homebrew Autoupdate is to do the same thing as the built in autoupdate (check for updates and show a list of outdated packages), but in the background.

**Comment by swissbuechi** [comment]
> All I need from Homebrew Autoupdate is to do the same thing as the built in autoupdate (check for updates and show a list of outdated packages), but in the background.

Where would you want the outdated packages to be displayed? In the notification?

> This makes it easier to miss updates than using the built in autoupdate, which is the opposite of what Homebrew Autoupdate is trying to achieve.

Couldn't you just run `brew outdated` before manually starting the upgrade?

**Comment by keyansheng** [comment]
Upon further investigation, it seems like the problem is due to the notification only showing the last line of the output.

 This is what the notification centre looks like when there are outdated packages:

>>> **brew-autoupdate**
>>> **Already up-to-date**
>>> Homebrew has been updated

Upon expanding the notification group, it looks like this:

> **brew-autoupdate**
> **Already up-to-date**
> Homebrew has been updated

> **brew-autoupdate**
> **Already up-to-date**
> Homebrew has been updated

> **brew-autoupdate**
> **or list it with brew outdated.**
> Homebrew has been updated

This is confusing since it's not clear that there are outdated packages, and completely hides `You have n outdated formulae installed.` from the user, since that message will not be shown on subsequent invocations of `brew`.

It would be less confusing to show the first line of the output instead (and possibly the list of outdated packages too, if space permits), to make it clear that there are outdated packages.
