### ISSUE TITLE
Do not use `--greedy` by default

### ISSUE THREAD

**Issue by jaklan** [Homebrew/homebrew-autoupdate#58]
[This commit](https://github.com/Homebrew/homebrew-autoupdate/commit/24c4193f89280b3ec38722010623ae2971dc5072) introduced `--greedy` flag always when using `--upgrade` option:

https://github.com/Homebrew/homebrew-autoupdate/blob/24c4193f89280b3ec38722010623ae2971dc5072/lib/autoupdate/start.rb#L17-L21

It shouldn't be the default behaviour, for the same reasons it's not default for `brew` (as described in [brew docs](https://docs.brew.sh/FAQ#why-some-apps-arent-included-in-upgrade)).

Solution? E.g. additional flag: `--greedy-upgrade`.

**Comment by DomT4** [comment]
This seems a valid enough request to me. I'd accept a PR to add a flag & related code changes, or I can try and look at it myself hopefully Sunday sometime.

**Comment by mlegenhausen** [comment]
This option seems to make trouble with the `google-cloud-sdk` package. It seems that during the update this package gets partially removed and is broken afterwards only a reinstallation via `brew reinstall -f google-cloud-sdk` solves the problem. Removing `--greedy` solved the issue for now.

I am using `brew autoupdate --start --upgrade --cleanup`.

**Comment by erikw** [comment]
I completely agree. Every day Firefox.app is shut down while I use it because it's being upgrade due to `--greedy`.

`--greedy` should be opt-in for homebrew-autoupdate!

**Comment by erikw** [comment]
I think something as simple as #81 can fix this issue!
