### ISSUE TITLE
New flag --upgrade-cask

### ISSUE THREAD

**Issue by rechandler12** [Homebrew/homebrew-autoupdate#60]
I suggest to introduce new flag `--upgrade-cask` and `--upgrade-cask-greedy` according to https://github.com/Homebrew/homebrew-autoupdate/issues/58. I think separation formulas from casks upgrades would be more convenient.

**Comment by DomT4** [comment]
The behaviour has been changed so `--greedy` is opt-in as of https://github.com/Homebrew/homebrew-autoupdate/commit/f8c3ba6fd150e7187e9b65e8847dd904d6aa3616.
