### ISSUE TITLE
Not working - Not updating outdated packages

### ISSUE THREAD

**Issue by petebocken** [Homebrew/homebrew-autoupdate#88]
I installed a few days ago and I get the notifications that "Homebrew has been updated", however when I run `brew outdated`, I still have some packages with available updates.
```
python@3.10 (3.10.2) < 3.10.4
rclone (1.58.0) < 1.58.1
powershell (7.2.2) != 7.2.3
```
log shows:
```
Sun May  1 14:38:37 CDT 2022
Already up-to-date.
Sun May  1 14:39:31 CDT 2022
Already up-to-date.
Sun May  1 14:41:05 CDT 2022
Already up-to-date.
```

I tried deleting the plist with `brew autoupdate delete` and reinstalled with `brew autoupdate start`. Manually adjusted the launchd schedule to run in a few mins, receive the macOS notification that it is again been updated, but the packages do not update.

**Comment by DomT4** [comment]
You need to pass `--upgrade` with the `start` command if you want it to automatically upgrade your packages too.
