### ISSUE TITLE
[Question] Source Code for the notifier

### ISSUE THREAD

**Issue by mietzen** [Homebrew/homebrew-autoupdate#91]
I would love to understand how you got the notifier working with your own Icon, since `terminal-notifier` and several other projects are no longer working. 

Did you write the notifier yourself? And would you mind sharing it source code?

**Comment by mietzen** [comment]
Is this the project you're using for the notifications? https://github.com/dataJAR/Notifier

**Comment by virbyte** [comment]
> Is this the project you're using for the notifications? https://github.com/dataJAR/Notifier

no, Homebrew-autoupdate uses an AppleScript applet - it's in the repo...

**Comment by DomT4** [comment]
Better late than never on my reply but @virbyte is correct; the notification here is provided by a very simple _(too simple, really)_ AppleScript that has a custom icon & is code-signed for reassurance. https://github.com/dataJAR/Notifier looks like an interesting project though and it's nice to see something in this space replacing `terminal-notifier` after the effective abandonment of that project.
